### ISSUE TITLE
Análisis de archivo de imagen en TXT

### ISSUE THREAD

**Issue by kala855** [labsirius/superficies#1]
La idea es que de manera visual se inspeccione el archivo, recuerden que tiene tres campos, cada uno haciendo referencia a las coordenadas X,Y y Z respectivamente.

**Comment by Jorge9314** [comment]
Buen día, Tengo dudas respecto a mis actividades para ir realizando con el documento. Ya lo he revisado y entiendo que estamos pendientes de pasarlo a un documento binario a través de C. Estuve revisando el gnuplot y concuerdo con Anderson que el tiempo de ejecución es lento. Espero mas información
